insert into cidade (cid_id, cid_nome, cid_uf) values (1, 'São Paulo', 'SP');
insert into cidade (cid_id, cid_nome, cid_uf) values (2, 'Rio de Janeiro', 'RJ');
insert into cidade (cid_id, cid_nome, cid_uf) values (3, 'Belo Horizonte', 'MG');
insert into cidade (cid_id, cid_nome, cid_uf) values (4, 'Salvador', 'BA');
insert into cidade (cid_id, cid_nome, cid_uf) values (5, 'Fortaleza', 'CE');
insert into cidade (cid_id, cid_nome, cid_uf) values (6, 'Brasília', 'DF');
insert into cidade (cid_id, cid_nome, cid_uf) values (7, 'Curitiba', 'PR');
insert into cidade (cid_id, cid_nome, cid_uf) values (8, 'Recife', 'PE');
insert into cidade (cid_id, cid_nome, cid_uf) values (9, 'Porto Alegre', 'RS');
insert into cidade (cid_id, cid_nome, cid_uf) values (10, 'Manaus', 'AM');
insert into cidade (cid_id, cid_nome, cid_uf) values (11, 'Belém', 'PA');
insert into cidade (cid_id, cid_nome, cid_uf) values (12, 'Goiânia', 'GO');
insert into cidade (cid_id, cid_nome, cid_uf) values (13, 'São Luís', 'MA');
insert into cidade (cid_id, cid_nome, cid_uf) values (14, 'Maceió', 'AL');
insert into cidade (cid_id, cid_nome, cid_uf) values (15, 'Teresina', 'PI');
insert into cidade (cid_id, cid_nome, cid_uf) values (16, 'Natal', 'RN');
insert into cidade (cid_id, cid_nome, cid_uf) values (17, 'João Pessoa', 'PB');
insert into cidade (cid_id, cid_nome, cid_uf) values (18, 'Aracaju', 'SE');
insert into cidade (cid_id, cid_nome, cid_uf) values (19, 'Campo Grande', 'MS');
insert into cidade (cid_id, cid_nome, cid_uf) values (20, 'Cuiabá', 'MT');
insert into cidade (cid_id, cid_nome, cid_uf) values (21, 'Palmas', 'TO');
insert into cidade (cid_id, cid_nome, cid_uf) values (22, 'Macapá', 'AP');
insert into cidade (cid_id, cid_nome, cid_uf) values (23, 'Rio Branco', 'AC');
insert into cidade (cid_id, cid_nome, cid_uf) values (24, 'Boa Vista', 'RR');
insert into cidade (cid_id, cid_nome, cid_uf) values (25, 'Porto Velho', 'RO');
insert into cidade (cid_id, cid_nome, cid_uf) values (26, 'Florianópolis', 'SC');
insert into cidade (cid_id, cid_nome, cid_uf) values (27, 'Vitória', 'ES');
commit;

insert into unidade (unid_id, unid_nome, unid_sigla) values (1, 'Unidade Básica de Saúde', 'UBS');
insert into unidade (unid_id, unid_nome, unid_sigla) values (2, 'Hospital Geral', 'HG');
insert into unidade (unid_id, unid_nome, unid_sigla) values (3, 'Clínica da Família', 'CF');
insert into unidade (unid_id, unid_nome, unid_sigla) values (4, 'Centro de Especialidades', 'CE');
insert into unidade (unid_id, unid_nome, unid_sigla) values (5, 'Pronto Socorro', 'PS');
insert into unidade (unid_id, unid_nome, unid_sigla) values (6, 'Unidade de Pronto Atendimento', 'UPA');
insert into unidade (unid_id, unid_nome, unid_sigla) values (7, 'Hospital Infantil', 'HI');
insert into unidade (unid_id, unid_nome, unid_sigla) values (8, 'Hospital Psiquiátrico', 'HP');
insert into unidade (unid_id, unid_nome, unid_sigla) values (9, 'Centro de Referência em Saúde Mental', 'CRSM');
insert into unidade (unid_id, unid_nome, unid_sigla) values (10, 'Unidade de Terapia Intensiva', 'UTI');
insert into unidade (unid_id, unid_nome, unid_sigla) values (11, 'Secretaria de Planejamento de Mato Grosso', 'SEPLAG-MT');
insert into unidade (unid_id, unid_nome, unid_sigla) values (12, 'Perícia Oficial e Identificação Técnica de Mato Grosso', 'POLITEC-MT');
commit;